kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: database
  creationTimestamp:
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp:
      labels:
        service: database
    spec:
      containers:
      - name: database
        image: mysql:5.7
        args:
          - "--ignore-db-dir=lost+found"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "P5Oe4EP9gziWzOY4mD"
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 200m
            memory: 500Mi
        volumeMounts:
        - name: mysql-data-2
          mountPath: /var/lib/mysql
        - name: mysql-data
          mountPath: /mysql-old
        - name: mysql-data-3
          mountPath: /etc/mysql/conf.d
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-claim
        - name: mysql-data-2
          persistentVolumeClaim:
            claimName: mysql-2-data-claim
        - name: mysql-data-3
          persistentVolumeClaim:
            claimName: mysql-3-data-claim
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 2


status: {}
