kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-3-data-claim
  annotations:
      volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
