kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data-claim
  annotations:
      volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
status: {}

# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: mysql-conf-data-claim
#   annotations:
#       volume.beta.kubernetes.io/storage-class: "standard"
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# status: {}
