kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: web
  creationTimestamp:
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp:
      labels:
        service: web
    spec:
      containers:
      - name: web
        image: 355645112541.dkr.ecr.us-east-1.amazonaws.com/iregua/web:latest
        args:
        - "/tmp/docker_run.sh"
        env:
        - name: DB_SERVER
          value: "database"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWD
          value: "P5Oe4EP9gziWzOY4mD"
        - name: DB_PREFIX
          value: "_ps"
        - name: DB_NAME
          value: "prestashop"
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /admin229qdvahf
            port: 80
          initialDelaySeconds: 300
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /admin229qdvahf
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        volumeMounts:
        - name: prestashop-data
          mountPath: /var/www/html/modules
        - name: prestashop-data
          mountPath: /var/www/html/themes
        - name: prestashop-data
          mountPath: /var/www/html/override
        - name: prestashop-data
          mountPath: /var/www/html/img
      volumes:
        - name: prestashop-data
          persistentVolumeClaim:
            claimName: prestashop-data-claim
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # maxUnavailable: 20%
      maxUnavailable: 1
      maxSurge: 2
status: {}
